# ⚠️ DEPRECATED: This workflow is deprecated and has been replaced by unified-update.yml
# Please use unified-update.yml instead for all daily updates
# This file is kept for reference but should not be run

name: Dev Quotes Update

on:
  # Disabled schedule to prevent duplicate runs
  # schedule:
  #   # Runs every day at 8 AM UTC
  #   - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual trigger only

jobs:
  update-quote:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update Daily Quote
      run: |
        python scripts/update_quote.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Quote Bot"
        git add README.md
        git diff --staged --quiet || git commit -m "💡 Daily quote update"
        git push
