# ⚠️ DEPRECATED: This workflow is deprecated and has been replaced by unified-update.yml
# Please use unified-update.yml instead for all daily updates
# This file is kept for reference but should not be run

name: Update README with Dynamic Content

on:
  # Disabled schedule to prevent duplicate runs
  # schedule:
  #   # Runs every 6 hours
  #   - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual trigger only
  # Disabled push triggers
  # push:
  #   branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Update README
      run: |
        python scripts/update_readme.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "🤖 Auto-update README with latest stats"
        git push
